name: Check Pods
on:
  push:
    branches: [main]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        proxy_host: ${{ secrets.PROXY_HOST }}
        proxy_port: ${{ secrets.PROXY_PORT }}
        proxy_username: ${{ secrets.PROXY_USER }}
        proxy_password: ${{ secrets.PROXY_PASS }}
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        script: |
          ip a
          kubectl get pods -A > output.log
    - name: Check Crash pods
      id: check-pods
      run: |
        echo "$(cat  output-pods.log | grep -v Running)" >> crash_report 2>&1
        echo "pods-dont-work=$(cat output-pods.log | grep -v 'Running\|Completed ' | wc -l)" >> $GITHUB_OUTPUT

    - name: Upload Crashed Pods List
      if: steps.check-pods.outputs.pods-dont-work != 1
      uses: actions/upload-artifact@v3
      with:
        name: Dead pods
        path: output-pods.log